#!/bin/bash
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0;37m'
bd='\e[1m'

MYIP=$(wget -qO- ifconfig.me/ip);
echo "Checking VPS"
clear
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}          • MENU TROJAN*GO •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e""
echo -e "[${CYAN}•1${NC}] $bd Create Trojan Account ${NC}"
echo -e "[${CYAN}•2${NC}] $bd Deleting Trojan Account ${NC}"
echo -e "[${CYAN}•3${NC}] $bd Renew Trojan Account ${NC}"
echo -e "[${CYAN}•4${NC}] $bd Check User Login Trojan ${NC}"
echo -e ""
echo -e "[${RED}•x${NC}] ${RED} Menu${NC}"
echo -e ""
read -p "     Please Input Number  [1-4 or x] :  "  menu
echo -e ""
case $menu in
1)
addtrgo
;;
2)
deltrgo
;;
3)
renewtrgo
;;
4)
cektrgo
;;
x)
exit
;;
*)
echo "Please enter an correct number"
sleep 1
menu-trgo
;;
esac
